// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykwltcncztlbpvcilxyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrd2x0Y25jenRsYnB2Y2lseHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNDYyMTIsImV4cCI6MjA4NDYyMjIxMn0.Oi1epGedMUt0TKOBKg4W30n_xIjZ5HmBjm0VHPM2fF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});